Repository fga-eps-mds/2018.2-Kalkuli, pull requests merged in 2018-10, with the labels that each got.

#132 Solve 118 Planejamento Sprint 6
  README.md
  docs/Sprint-5-Resultados.md
  docs/Sprint-6.md
  docs/assets/quadro-de-pareamento-s6.png
  website/sidebars.json
Labels: Documentation, EPS, Tech Leader

#135 Solve #129 AjustarWiki
  README.md
  docs/Definicao-Done.md
  docs/DocumentoDeVisao.md
  docs/Sprint-1-Resultados.md
  docs/Sprint-5-Resultados.md
  docs/assets/AreadeNotas.png
  docs/assets/ComparacaodeNotas.png
  docs/assets/CriarTag.png
  docs/assets/Dashboard.png
  docs/assets/DragFile.png
  docs/assets/Home Page.png
  docs/assets/Tags.png
  docs/deploy.md
  docs/identidadeVisual.md
  website/core/Footer.js
  website/i18n/en.json
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
  website/static/css/animation.css
  website/static/css/card.css
  website/static/css/custom.css
  website/static/css/features.css
  website/static/css/footer.css
  website/static/css/header.css
  website/static/css/reset.css
  website/static/css/typography.css
  website/static/img/members/git.png
  website/static/img/members/link.png
Labels: Documentation, Hotfix, MDS, UI & UX

#158 Solve 149 Resultados Sprint 7
  docs/Sprint-4-Resultados.md
  docs/Sprint-7-Resultados.md
  docs/Sprint-8.md
  docs/assets/BurndowndeRiscos-S7.png
  docs/assets/Conhecimento-S7.png
  docs/assets/Retrospectiva-S7.png
  docs/assets/burndown-S7.png
  docs/assets/velocity-S7.png
  docs/overview.md
  docs/release.md
  docs/roadmap.md
  website/pages/en/index.js
  website/sidebars.json
  website/siteConfig.js
Labels: Documentation, EPS, Tech Lead
