Repository fga-eps-mds/2018.2-Kalkuli, pull requests merged in 2018-09, with the labels that each got.

#30 Solve #15 Iniciar o Community Profile do repositório
  CONTRIBUTING.md
Labels: Documentation, EPS

#61 Planejamento Sprint 3
  docs/EstruturaAnalitica.md
  docs/Sprint-2-Resultados.md
  docs/Sprint-3.md
  docs/assets/EAP-Versao-1.png
  website/i18n/en.json
  website/sidebars.json
Labels: Documentation, EPS, Tech Leader

#65 Criar o Plano de Medição
  docs/assets/legendaConhecimento.png
  docs/medicao.md
  website/i18n/en.json
  website/sidebars.json
Labels: Documentation, EPS, Tech Leader

#63 Solve 51 Refinar Documento de Arquitetura
  docs/CONTRIBUTING.md
  docs/DocumentoDeArquitetura.md
  docs/assets/GitFlow.png
  docs/assets/ModelagemDados.png
  docs/assets/Pipeline_Desenvolvimento.png
  docs/assets/ReactReduxDiagram.png
  docs/assets/RepresentacaoArquitetural.png
  docs/assets/diagramaPacotes.png
  website/i18n/en.json
  website/package-lock.json
  website/sidebars.json
Labels: Architecture

#70 Solve 68 Resultados Sprint 3
  docs/Sprint-2-Resultados.md
  docs/Sprint-3-Resultados.md
  docs/Sprint-3.md
  docs/assets/BurndowndeRiscos-S3.png
  docs/assets/Conhecimento-S3.png
  docs/assets/Retrospectiva-S3.png
  docs/assets/burndown-S3.png
  docs/assets/velocity-S3.png
  docs/medicao.md
  website/sidebars.json
  website/siteConfig.js
Labels: Documentation, EPS, Tech Leader

#82 Solve 68 Planejamento Sprint 4
  docs/Sprint-4.md
  docs/assets/quadro-de-pareamento-s4.png
  website/sidebars.json
Labels: Documentation, EPS, Tech Leader

#84 Solve 83 Hotfix - Atualizar diagramas de Arquitetura
  docs/assets/ModelagemDados.png
  docs/assets/RepresentacaoArquitetural.png
Labels: Architecture, Documentation, EPS, Hotfix

#90 Solve 88 Resultados Sprint 4
  docs/Sprint-3-Resultados.md
  docs/Sprint-4-Resultados.md
  docs/assets/BurndowndeRiscos-S4.png
  docs/assets/Conhecimento-S4.png
  docs/assets/Retrospectiva-S4.png
  docs/assets/burndown-S4.png
  docs/assets/velocity-S4.png
  docs/comunicacao.md
  docs/overview.md
  website/sidebars.json
  website/siteConfig.js
Labels: Documentation, EPS, Tech Leader

#111 Solve 98 Pontuar Sprints Anteriores
  docs/Sprint-0-Resultados.md
  docs/Sprint-1-Resultados.md
  docs/Sprint-1.md
  docs/Sprint-2-Resultados.md
  docs/Sprint-2.md
  docs/Sprint-3-Resultados.md
  docs/Sprint-4-Resultados.md
  docs/assets/burndown-S0.png
  docs/assets/burndown-S1.png
  docs/assets/velocity-S0.png
  docs/assets/velocity-S1.png
  docs/sprint0.md
Labels: Documentation, EPS, Product Manager, Tech Leader

#113 Solve #96 refatorarDocumentoArquitetura
  docs/DocumentoDeArquitetura.md
  docs/assets/DiagramadePacotesFlask.png
  docs/assets/ModelagemDados.png
  docs/assets/ModelagemdeDados.png
  docs/assets/Pipeline_Desenvolvimento.png
  docs/assets/React-Redux.png
  docs/assets/ReactReduxDiagram.png
  docs/assets/RepresentacaoArquitetural.png
  docs/assets/RepresentaçãoArquitetural.png
  docs/assets/diagramaPacotes.png
Labels: Architecture, Documentation, MDS

#114 Solve #95 RefatorarDocumentoVisão
  docs/DocumentoDeVisao.md
Labels: Documentation, MDS

#115 Solve 99 Corrigir Layouts da Wiki
  website/core/Footer.js
  website/pages/en/index.js
  website/siteConfig.js
  website/static/css/card.css
  website/static/css/features.css
  website/static/css/footer.css
  website/static/css/typography.css
  website/static/img/doc.png
  website/static/img/github.png
  website/static/img/kalkui.png
Labels: Documentation, EPS

#128 Solve #121EvoluirIdentidadeVisual
  docs/identidadeVisual.md
Labels: Documentation, MDS, UI & UX

#131 Solve 117 Resultados Sprint 5
  README.md
  docs/Sprint-2-Resultados.md
  docs/Sprint-3-Resultados.md
  docs/Sprint-4-Resultados.md
  docs/Sprint-5-Resultados.md
  docs/Sprint-5.md
  docs/assets/BurndowndeRiscos-S5.png
  docs/assets/Conhecimento-S5.png
  docs/assets/Retrospectiva-S5.png
  docs/assets/burndown-S5.png
  docs/assets/velocity-S5.png
  website/sidebars.json
Labels: Documentation, EPS, Tech Leader

#133 Solve #122 ComplementarDocumentoDeArquitetura
  docs/DocumentoDeArquitetura.md
  docs/assets/React-Redux-Async.png
  docs/assets/React-Redux-Sync.png
  docs/assets/React-Redux.png
Labels: Architecture, Documentation, MDS
